STATELESS:
  reset-quick-edit: true
  save-session: false
  auto-file-manipulation: false
  lyrics-file-format: .lrc

STATEFULL:
  win-width: 800 # 360 min
  win-height: 600 # 100 min
  maximized: false
  opened-dir: null
  sort: 1